[build]
  command = "CI= npm run build"
  publish="./build"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKENDURL = "http://localhost:8080"
